#!/usr/bin/perl -w
use strict;

#####################################################################################
#                               fastq2fasta.pl                                      #
#####################################################################################
# This program creates a FASTA format read file for each FASTQ read file            #
#                                                                                   #
#    Inputs:                                                                        #
#                a list of FASTQ read files specified on the command line           #
#    Outputs:                                                                       #
#                a FASTA read file for each input file                              #
#####################################################################################

# Print help message if the only argument is "-h"
if (@ARGV == 1 && $ARGV[0] eq '-h') {
    print "Usage:\n\t$0 <read1.fastq> <read2.fastq>\n";
    print "\n\tFor each fastq file the program will create a fastq file with 'renamed_' prefix\n";
    exit 0;
}

# Create the FASTA read file for each input file
for my $in (@ARGV) {
    my $out = "renamed_" . $in;
    if (-e $out) {
        print "$out file already exists, please rename it or remove it before running this program\n";
        next;
    }
    `cat $in | awk '{if(++count%4==1) {++read; print "@"read;} else {print \$0;}}' >$out`;
}
